name: Continuous Deployment

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      # 1. Compare branch 코드 내려 받기
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.push.base_ref }}

      # 2. SSH ACTION을 통한 Run-Command
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            script: |
              cd /home/ubuntu/OnlineNews_FE/
              git reset --hard HEAD
              git clean -fd
              
              git pull origin main
              npm install
          
              # Vite 프로젝트 빌드
              npm run build
          
              # Nginx 재시작 (빌드 결과물 서빙)
              sudo systemctl restart nginx

