name: Continuous Deployment

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      # 1. Compare branch 코드 내려 받기
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.push.base_ref }}

      # 2. SSH ACTION을 통한 Run-Command
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd /home/ubuntu/OnlineNews_FE/
            pwd 
            git status
            git reset --hard HEAD
            git clean -fd
            git pull origin main
            npm run install
            npm run build
            nohup npm run dev -- --host 0.0.0.0 > app.log 2>&1 &
            sudo systemctl restart nginx  

